name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    # 1. 리포지토리 체크아웃
    - 
      name: Checkout repository
      uses: actions/checkout@v4
    
    # 2. Docker 로그인
    - 
      name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    # 3. Tag를 변수로 저장
    - 
      name: Set date variable
      run: |
        DATE_TAG=$(date +%Y%m%d%H%M%S)
        echo "DATE_TAG=${DATE_TAG}" >> $GITHUB_ENV
        
    # 4. Docker Image Build And Push
    -
      name: Docker Image Build And Push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ secrets.REGISTRY_URL }}/pipeline-test:${{ DATE_TAG }}
