name: Build and Upload to Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build And Rename JAR file
        run: | 
          ./mvnw clean package -DskipTests
          cp target/*.jar ./app.jar

      - name: Upload JAR file to Deploy
        run: |
          curl -X POST \
            -F "binaryFile=@./app.jar" \
            -F "applicationType=server" \
            https://api-deploy.nhncloudservice.com/api/v1.0/projects/tvheufmYlhFFFBofvq1Fzr6XoRnj6PSCz2pAqzSPM6xc3bmBIaOtZSjY4sHmWxm8/artifacts/5686/binary-group/12142 \
            -H "Content-Type: multipart/form-data"
