name: Build and Upload to Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build And Rename JAR file
        run: | 
          ./mvnw clean package -DskipTests
          cp target/*.jar ./app.jar

      - name: Upload JAR file to Deploy
        run: |
          curl -X POST \
          'https://api-tcd.nhncloudservice.com/api/v1.0/projects/8ui0bQSSQkObH8ED/artifacts/4353/binary-group/5241' \
          -F "binaryFile=@./app.jar" \
          -F "applicationType=server" \
          -H "Content-Type: multipart/form-data"
