name: Build and Upload to S3

on:
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build And Rename JAR file
        run: | 
          ./mvnw clean package -DskipTests
          cp target/*.jar ./app.jar

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.S3_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ vars.S3_REGION }}

      - name: Upload JAR file to S3
        run: |
          aws s3 cp ./app.jar s3://github-actions-test/deploy-ksh/app.jar \
           --endpoint-url ${{ vars.S3_ENDPOINT }}
